force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VacationRequest__c/VacationRequest__c.object-meta.xml
<CustomObject>
    <label>VacationRequest</label>
    <nameField>
        <label>VacationRequest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VacationRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VacationRequest__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>VacationRequests</relationshipLabel>
    <relationshipName>VacationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SendMailVacationRequestTriggerTest.cls
@isTest
public class SendMailVacationRequestTriggerTest {
    @isTest
    public static void SendMailVacationRequestTriggerTest() {
        Employee__c employee = new Employee__c();
        employee.name = 'meryemahmada.97';
        insert employee;
        VacationRequest__c vc = new VacationRequest__c();
        vc.name = 'congé';
        vc.employee__c = employee.id;
        insert vc;
    }
}